### ISSUE TITLE
it seems doesn't support utf8

### ISSUE THREAD

**Issue by holyzhou** [lukecyca/pyzabbix#52] opened 2015-01-27 04:34 UTC
hello , sorry bother you,  but i got question want to ask. in few days , i work on vcenter minitor  use project called py-vpoller  which they use you pyzabbix package. when i import vcenter vm hosts to zabbix hosts use zabbix-vsphere-import  tool (https://github.com/dnaeon/py-vpoller/tree/master/extra/zabbix/vsphere-import)  , it return error 

"""
 File "build/bdist.linux-x86_64/egg/pyzabbix/__init__.py", line 154, in fn
 File "build/bdist.linux-x86_64/egg/pyzabbix/__init__.py", line 129, in do_request
UnicodeEncodeError: 'ascii' codec can't encode characters in position 56-59: ordinal not in range(128)
"""

in zabbix-vsphere-import script , it pass hostname to pyzabbix,but my hostname have chinese character，so , i think maybe it doesn't support utf8.

**Comment by neothematrix** [comment] 2015-01-27 15:28
hello holyzhou, what python version are you using? 2.x or 3.x? in case you're using 2.x, could you try with 3.x?

**Comment by neothematrix** [comment] 2015-01-27 16:06
It would be nice to have some more stack trace, not just the pyzabbix part, but also the py-vpoller part, to try and understand which part is having issues.
Just for your information, the "host" property in Zabbix cannot have chinese characters, only the "visible name" that is the "name" property.
I tried to create an host with chinese character in the "Visible name" using the API and it succeeded and then I tried the "host.get" API call and it returned the correctly encoded character:

```
>>> zapi.host.get(hostids='11364',output=['name'])
[{'hostid': '11364', 'name': u'\u8f93\u5165'}]

>>> print zapi.host.get(hostids='11364',output=['name'])[0]['name']
输入
```

so I suppose it may either be a problem in the encoded name returned by the vpoller call or something else, but we'll need more information

**Comment by dnaeon** [comment] 2015-01-28 11:16
Hi,

This is indeed related to Zabbix not supporting unicode characters as part of the machine name (`{HOST.HOST}` macro). Only unicode characters in the visible name are supported (the `{HOST.NAME}` macro).

Here are the corresponding issues in vPoller and Zabbix as well:

* https://github.com/dnaeon/py-vpoller/issues/120
* https://github.com/dnaeon/py-vpoller/issues/95
* https://support.zabbix.com/browse/ZBX-3111

So, this issue can be closed as the issue is not related to pyzabbix or vPoller.

Regards,
Marin

**Comment by neothematrix** [comment] 2015-02-13 17:09
luke, I think we can close this

**Closed** 2015-02-13 17:13 UTC
