### ISSUE TITLE
certificate verify failed error when trying to connect to Zabbix

### ISSUE THREAD

**Issue by FlanniganColum** [lukecyca/pyzabbix#219] opened 2023-10-03 16:16 UTC
Hey.
   I am trying out this module and i get an SSL error and i am running the latest version, is there a bug in this version for SSL and should i be using an older version

Version:
Zabbix: 
6.0.16

python --version
Python 3.6.15

pip list | grep -i zabbix
pyzabbix           1.3.0

Error:
```python
Sending: {'jsonrpc': '2.0', 'method': 'apiinfo.version', 'params': {}, 'id': 0}
Traceback (most recent call last):
  File "/opt/apps/zabbix/availability/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/opt/apps/zabbix/availability/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/apps/zabbix/availability/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/apps/zabbix/availability/venv/lib/python3.6/site-packages/urllib3/connection.py", line 424, in connect
    tls_in_tls=tls_in_tls,
  File "/opt/apps/zabbix/availability/venv/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 450, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "/opt/apps/zabbix/availability/venv/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib64/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)
```

Script:
```python
def zbx_login():
    try:
        zapi = ZabbixAPI(custom_config.zabbix_url)
        #zapi.login("{}".format(custom_config.zabbix_user), "{}".format(custom_config.zabbix_password))
        zapi.login(api_token='XxXxXxXxXxXxXx')

        # Disable SSL certificate verification
        zapi.session.verify=False

        # Specify a timeout (in seconds)
        zapi.timeout=5.1

        print("Connected to Zabbix API Version %s" % zapi.api_version())

    except Exception as e:
        logging.error("Error: {}".format(str(e)))
        print(traceback.format_exc())
        sys.exit(1)
```

**Comment by jooola** [comment] 2023-10-03 16:23
Duplicate of https://github.com/lukecyca/pyzabbix/issues/167

**Closed by jooola** 2023-10-03 16:23 UTC

**Comment by FlanniganColum** [comment] 2023-10-03 16:39
The other issues are closed and related to different this. I am running the latest version but yet still have the issue.. #165 was related to version as per my description i am running the latest. can you advise here?

**Comment by jooola** [comment] 2023-10-03 16:45
See https://requests.readthedocs.io/en/latest/user/advanced/#ssl-cert-verification

Or, as described in #167:

```
session = requests.Session()
session.verify = False
zapi = ZabbixAPI("https://some-zabbix.com", session=session)
```

**Comment by lukecyca** [comment] 2023-10-03 16:50
[According to the README](https://github.com/lukecyca/pyzabbix#customizing-the-http-request), this should also work:

```
zapi = ZabbixAPI(custom_config.zabbix_url)
zapi.session.verify=False
zapi.login(api_token='XxXxXxXxXxXxXx')
```

The problem with OP's code is that it's setting `verify = False` _after_ trying to log in. Since the login request is happening prior to disabling SSL verification, it will fail to verify.

**Comment by FlanniganColum** [comment] 2023-10-03 16:52
yes i have the zapi.session.verify=False but that does not work, however setting the session in the requests seems to work. i guess the zapi side has bugs

**Comment by jooola** [comment] 2023-10-03 16:54
@lukecyca Haha, overlooked this one.

@FlanniganColum Please read the answer from @lukecyca I beleive this is your fix.
