### ISSUE TITLE
Errors with create groups and users

### ISSUE THREAD

**Issue by rami-sergey** [lukecyca/pyzabbix#93] opened 2017-09-19 15:36 UTC
Zabbix 3.4, into zabbix-ldap-sync:
1.
this:
        result = self.conn.usergroup.create(name=group, permission=3)
I change to:
        result = self.conn.usergroup.create(name=group)
because otherwise we have an error:
pyzabbix.ZabbixAPIException: (u'Error -32602: Invalid params., Invalid parameter "/1": unexpected parameter "permission".', -32602)
because wrong syntax:
sending:
"params": {
        "name": "GroupA",
        "permission": 3
 }
but need:
"params": {
        "name": "GroupA",
        "rights": {
            "permission": 3,
            "id": "2"
        }
}
About "id": "2" - don't known, taken from the documentation.

2.
after:
                    user['surname'] = ldap_conn.get_user_sn(ldap_users[eachUser])
I add:
                    if not user['surname']:
                        user['surname'] = ''
without this changes we have an error when surname field is not filled:
pyzabbix.ZabbixAPIException: (u'Error -32602: Invalid params., Invalid parameter "/1/surname": a character string is expected.', -32602)
because:
    "params": [
        {
            "alias": "test",
            "surname": null,
            "name": "test",
            ...
        }
    ],

**Comment by neothematrix** [comment] 2017-10-10 10:01
your api call is wrong (or maybe zabbix-ldap-sync api call is wrong), permission=3 is not correct: 
https://www.zabbix.com/documentation/3.4/manual/api/reference/usergroup/create

permission is an attribute under the "rights" node, so your call should be:

self.conn.usergroup.create(name=group, rights={"permission": 3, "id": 2})

**Comment by rami-sergey** [comment] 2017-10-10 15:31
It's not my api. it's zabbix-ldap-sync api call is wrong. This documentation does not show a subquery. Thanks for your example.

**Comment by neothematrix** [comment] 2017-10-11 12:21
no problem, keep in mind that the whole "rights" array is not mandatory, you can skip it, and also, the "id": 2 means you are giving permission "3" (which is read/write) to the hostgroup with id "2", you may want to change that to the right hostgroup id for your installation since the id changes.

**Comment by rami-sergey** [comment] 2017-10-11 16:32
Closed? What about this? API does not understand "null" parameter in "surname" variable, but this parameter is not required.
after:
user['surname'] = ldap_conn.get_user_sn(ldap_users[eachUser])
I add:
if not user['surname']:
user['surname'] = ''
without this changes we have an error when surname field is not filled:
pyzabbix.ZabbixAPIException: (u'Error -32602: Invalid params., Invalid parameter "/1/surname": a character string is expected.', -32602)
because:
"params": [
{
"alias": "test",
"surname": null,
"name": "test",
...
}

**Comment by neothematrix** [comment] 2017-10-11 18:10
sorry I missed the second part of the issue.

that's really not a fault of the API implementation, if you pass the "surname" parameter to the call, pyzabbix will pass it to the Zabbix API, that's by design, it shouldn't be API implementation burden to check and remove "null" attributes, what if another Zabbix API call allows a "null" value for an attribute? The fact that the "surname" is not required means you don't need to define it at all.

The correct solution would be for https://github.com/dnaeon/zabbix-ldap-sync/blob/master/zabbix-ldap-sync to completely avoid defining the user['surname'], but also user['name'] attributes if the value returned from ldap is "null", you should open an issue to zabbix-ldap-sync.
Assigning to it a "" value is also a way (as you did) but less elegant in my opinion.

**Comment by rami-sergey** [comment] 2017-10-11 20:22
I'm about this: "a character string is expected." API requires only a string. By default this field is empty in LDAP. Is it possible to convert null to an empty string so that there are no such simple errors that stop the script? What can be wrong with this conversion?

**Comment by neothematrix** [comment] 2017-10-12 10:52
that error message is actually sent from the Zabbix API itself, not by pyzabbix. It basically says: if you pass me the "surname" attribute, it has to be a "string made of characters", otherwise, don't send it at all.
PyZabbix doesn't check the validity of the calls, it's not its duty, it just passes the parameters directly to the API endpoint.
As I said, it shouldn't be pyzabbix burden to check the validity (and proactively fix) the wrong API calls, like in this case, passing a null value to an optional attribute, as it may even lead to unexpected output from the API.
PyZabbix has no knowledge of which are the required or optional attributes as it passes everything to ZabbixAPI, this was done on purpose, so we don't have to rewrite every new or changed api method and the pyzabbix implementation is always ready.

**Comment by neothematrix** [comment] 2017-10-23 09:55
rami, I'm closing this now, feel free to reopen or open a new issue if you have topics related to the pyzabbix itself.
thanks!

**Closed by neothematrix** 2017-10-23 09:55 UTC
